# Generated by Django 5.0.1 on 2024-08-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApeCoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(max_length=255)),
                ('token_name', models.CharField(max_length=255, null=True)),
                ('token_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('token_amount', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('staking_pool', models.CharField(max_length=255, null=True)),
                ('staked_balance', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('staked_rewards', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('staked_usd_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
